# Configuration file for TravisCI
os: linux
dist: xenial
language: python
python: "3.6"

# Only build pushes to the master branch
branches:
  only:
    - master

# Install Tex on the OS
addons:
  apt:
    packages:
      - texlive-full

env:
  global:
    # Doctr deploy key for leouieda/cv
    - secure: "mlr5CPIF8Pfleulxnz422NKMzyE2KTg6X45Y/p7ROxFg3f7Aj8OGbz6dTZRGxw9C+PDVM7fPgNEmgbcZav1Ji4/AeiSJoJ0zVXigs/ACcHxOqVwKuigw9DR0HPr7ujFsSCrBi8w2pqJgZa+VzA5TTdvD0B2Vlpe/j6JQiePgV0k="

# Setup the build environment
install:
  # Install the requirements
  - pip install -r requirements.txt

# Build the PDF from the LaTeX file
script:
  - make
  - cd output
  - rm -f *.aux *.log *.bbl *.blg *.out *.toc
  - cd ..

#deploy:
  ## Push the PDF to the gh-pages branch so that it's served
  #- provider: script
    #script: doctr deploy . --built-docs output --key-path .github_deploy_key.enc
    #skip_cleanup: true
    #on:
      #branch: master

notifications:
  email: false
