# The name of the main .tex file to build.
# Other files can be included into this one.
CV = leonardo_uieda_cv
LETTER_RESEARCH = leonardo_uieda_research_statement
LETTER_SKILLS = leonardo_uieda_skills_statement

# Folder with the Latex source files
SRC = .

# Folder where the figure files are (will assume they are EPSs or PNGs)
FIGS = figures

# Folder where the BibTex .bib files are
BIB = .

# Folder where the .cls .bst and .sty style files are
STYLES = $(SRC)

# Folder where output will be placed
OUTPUT = output

### File Types (for dependencies)
STY_FILES = $(shell find $(STYLES) -maxdepth 1 -name '*.sty')
CLS_FILES = $(shell find $(STYLES) -maxdepth 1 -name '*.cls')
BST_FILES = $(shell find $(STYLES) -maxdepth 1 -name '*.bst')
EPS_FILES = $(shell find $(FIGS) -name '*.eps')
PNG_FILES = $(shell find $(FIGS) -name '*.png')

### Compilation Flags
LATEX_FLAGS  = -halt-on-error -output-directory $(OUTPUT)/

### Standard PDF Viewers
UNAME := $(shell uname)
ifeq ($(UNAME), Linux)
PDFVIEWER = evince
endif
ifeq ($(UNAME), Darwin)
PDFVIEWER = open
endif


# MAIN TARGETS
###############################################################################

all: cv research skills
cv: $(OUTPUT)/$(CV).pdf
research: $(OUTPUT)/$(LETTER_RESEARCH).pdf
skills: $(OUTPUT)/$(LETTER_SKILLS).pdf

show: all
	@ # Redirect stdout and stderr to /dev/null for silent execution
	@ (${PDFVIEWER} $(OUTPUT)/$(CV).pdf > /dev/null 2>&1 & )
	@ (${PDFVIEWER} $(OUTPUT)/$(LETTER_RESEARCH).pdf > /dev/null 2>&1 & )
	@ (${PDFVIEWER} $(OUTPUT)/$(LETTER_SKILLS).pdf > /dev/null 2>&1 & )

### Clean
# This target cleans the temporary files generated by the tex programs in
# use. All temporary files generated by this makefile will be placed in OUTPUT
# so cleanup is easy.
clean::
	rm -rf $(OUTPUT)/
	rm -rf $(FIGS)/*-eps-converted-to.pdf

$(OUTPUT)/:
	mkdir -p $(OUTPUT)/

$(OUTPUT)/%.pdf: $(SRC)/%.tex $(STY_FILES) $(CLS_FILES) $(PNG_FILES) $(EPS_FILES) | $(OUTPUT)/
	pdflatex $(LATEX_FLAGS) $<
	pdflatex $(LATEX_FLAGS) $< 1>/dev/null
