# Rules for compiling and showing the PDF from the LaTeX sources

# Configuration variables
OUTPUT_DIR = output
LATEX_FLAGS = -pdf -xelatex -output-directory=$(OUTPUT_DIR)/
LATEX = latexmk
PDFVIEWER = xdg-open

# Input files
TEX = $(wildcard *.tex)

# Output files
PDF = $(patsubst %.tex,$(OUTPUT_DIR)/%.pdf,$(TEX))

# TARGETS
###############################################################################

# Generate all PDFs
all: $(PDF)

# Open the PDFs in the specified viewer program
show: all
	@ # Redirect stdout and stderr to /dev/null for silent execution
	@ (${PDFVIEWER} $(PDF) > /dev/null 2>&1 & )

# Generate a PDF from a Tex file
$(OUTPUT_DIR)/%.pdf: %.tex
	mkdir -p $(OUTPUT_DIR)
	$(LATEX) $(LATEX_FLAGS) $<

# Clean the temporary files generated by the tex programs (including the PDFs)
clean:
	rm -rf *.aux *.log *.bbl *.blg *.out *.toc
	rm -rf $(OUTPUT_DIR)
